Update readme w/ instructions for installing ols console plugin
openshift/lightspeed-console pull request #19
Opened 2024-02-19 22:09 UTC by bparees

2024-02-19 22:09 UTC, bparees commented
@kyoto ptal.  I'm sure there's more stuff you want to have in here about how to develop on the console, run the plugin locally, etc, but this should at least make it so other people have instructions to follow for deploying it.

cc @sauagarwa

2024-02-20 00:23 UTC, bparees commented
note that also either the helm chart needs to be updated to setup the proxy, or the readme needs to direct people to do so, per:

https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1708386698179979?thread_ts=1708382393.728239&cid=C068JAU4Y0P

(i had to set authorization to "None" for now, also)

2024-02-20 03:13 UTC, kyoto requested changes
Thanks @bparees

I'd like to leave most of the text since it is relevant for this plugin. It mostly just needs references to "template" replacing with this plugin's name in a few places. I can do that after this PR merges.

2024-02-20 03:13 UTC, kyoto commented on README.md
> -to run in-cluster.
I think it's worth keeping these "Development" and "Docker image" sections since they are still relevant and explain how to do local development.

2024-02-20 03:13 UTC, kyoto commented on README.md
> -The cypress-report.html file is generated and should be in (/integration-tests/screenshots) directory
Lets's keep these "i18n", "Linting" and "Reporting" sections since they are still relevant.

2024-02-20 17:14 UTC, bparees commented
@kyoto updated.  My primary goal is to have instructions for people who want to install this and wire it up to OLS.  to that end, can you follow up on https://github.com/openshift/lightspeed-console/pull/19#issuecomment-1953307758 after this merges?

2024-02-21 01:32 UTC, kyoto commented
/lgtm

2024-02-21 02:09 UTC, kyoto commented
/approve

2024-02-21 02:26 UTC, merged